### ISSUE TITLE
Items unpredictable single result for non exact query

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/warframe-status#377]
Since the, [result criteria](https://github.com/WFCD/warframe-status/blob/main/src/controllers/wfItems.js#L140) for returning a non exact match, is being the last one in the items array, it turns out unpredictable between restarts, because the order might change.

I think there should be a criteria for non exact inclusive matching, like the length, the closest length distance between the item and the query should be the one returned.

Example: `https://api.warframestat.us/items/excalibur%20umbr`
Expected: `{ "name": "Excalibur Umbra" }`
Returned: `{ "name": "Noggle Statue - Excalibur Umbra" }`

**Comment by TobiTenno** [comment]
right. so that allowance comes from the `/items/search/:item` path... as for checking the very first one, i'm down with more options as query params.

currently it looks for exact as priority and overrides
we already have an option in place to allow the user to check any specific field

**Comment by TobiTenno** [comment]
I don't know that the "retured" example is even possible if you type the whole name? 

the problem i'm seeing is...

```diff
- https://api.warframestat.us/items/excalibur%20umbr
+ https://api.warframestat.us/items/excalibur%20umbra
```

**Comment by AyAyEm** [comment]
Oh.. the missing last letter is on purpose, Since we have an inclusion matching we can have that sort of query, but it's return value isn't reliable. A bit of edge case since you would probably use search instead of single item result, but it would be a nice to have feature.

**Comment by TobiTenno** [comment]
well... i think that's kinda the point of doing the whole name, tho

**Comment by AyAyEm** [comment]
```js
let distance;
....
    if (item[by].toLowerCase().includes(req.params.item.toLowerCase()) && !exact) {
      const newDistance = item[by].toLowerCase().replace(req.params.item.toLowerCase(), '').length;
      if (!distance || newDistance < distance) {
        distance = newDistance;
        result = item;
      }
    }
```
Something like this would solve the problem.

**Comment by TobiTenno** [comment]
so if you want all possibilities, you should use `/items/search/:item`, but if you have an exact result and just want one,  `/items/:item`

**Comment by TobiTenno** [comment]
> ```js
> let distance;
> ....
>     if (item[by].toLowerCase().includes(req.params.item.toLowerCase()) && !exact) {
>       const newDistance = item[by].toLowerCase().replace(req.params.item.toLowerCase(), '').length;
>       if (!distance || newDistance < distance) {
>         distance = newDistance;
>         result = item;
>       }
>     }
> ```
> 
> Something like this would solve the problem.

this looks good all but for the first check in your innermost if, since that would be true on `distance === 0`, which i'd assume you don't want to be true, as that would allow something with `distance === 1` (so 1 letter difference) to override an exact match

**Comment by AyAyEm** [comment]
Yes, but if the distance is 0 then it's an exact match and it wouldn't enter this block.

**Comment by AyAyEm** [comment]
> so if you want all possibilities, you should use `/items/search/:item`, but if you have an exact result and just want one, `/items/:item`

That's why it would be an edge case, but since we're using includes in one item search i guess it already deviates from that.

**Comment by AyAyEm** [comment]
So we could remove includes from one item search or we could be more precise on how we search for that item, both options are fine by me, just returning the last inclusive matching element in a unsorted array that doesn't fit too well with me.

**Comment by TobiTenno** [comment]
I guess I don't feel there's a _need_ to remove includes... non-exact queries are supposed to be... inexact? i'm fine with the distance solution if we wanna go that route, I just also don't feel that includes is intrinsically _wrong_
