### ISSUE TITLE
Language unstable

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-status#91]
After changes for #81 and #87 to support the correct structure of parsing, the language is not always being given in the requested language.

Some possibilities:
- first language cached during that period is always returned
- language mismatch when sent to the parser

I don't know which it is yet. I've not yet found the precise cause, but the first (caching) is more likely. This is the root of https://github.com/WFCD/warframe-hub/issues/344 as well.

**Comment by TobiTenno** [comment]
Resolved with 12cb9d26d922b2562d6089550635650367c79fdb

**Comment by PauloProphet** [comment]
This seems to have become an issue again, lately I've been receiving the results in chinese at random, and specifying the language in the header also doesn't seem to have an effect.

**Comment by TobiTenno** [comment]
yes, i've brought it up on the discord (you'd probably get good results joining the server), but you'll need to specify the language as a query string. sorry, it really sucks with how the caching goes.

**Comment by TobiTenno** [comment]
example is that if you use, say, `https://api.warframestat.us/pc` you'll need to specify it as `https://api.warframestat.us/pc/?language=en` (note the trailing `/`
