### ISSUE TITLE
I was blocked by cors.

### ISSUE THREAD

**Issue by Ryuuki6602** [WFCD/warframe-status#956]
![image](https://user-images.githubusercontent.com/95893742/229424123-123d3afd-dd99-4682-919e-3de944a65b79.png)

**Comment by TobiTenno** [comment]
yes, that's how CORS works... also, that's not our website

**Comment by Ryuuki6602** [comment]
LOL

**Comment by Ryuuki6602** [comment]
> yes, that's how CORS works... also, that's not our website

LOL.Embarrassed
